JDRaftKeeper/RaftKeeper

.clang-format
This PR try to fix #63 
Current clang-format configuration does not wrap lambda block, resulting inconsistency behavior between clang-format and check-style. `BeforeLambdaBody` can wrap lambda block, thus solving the inconsistency. Refer to [BeforeLambdaBody](https://clang.llvm.org/docs/ClangFormatStyleOptions.html) for more information.
=> Wrap lambda block

programs/server/Server.cpp, programs/server/config.xml, src/Common/getNumberOfPhysicalCPUCores.cpp, src/Service/Settings.cpp, tests/integration/test_four_word_command/configs/enable_keeper1.xml
This PR try to fix #6 
1. `getNumberOfPhysicalCPUCores` should take container into consideration
2. Set default thread_count to CPU core size.
3. Use `getNumberOfPhysicalCPUCores` for IO thread count.
=> Set default thread_count to CPU core size.

base/common/logger_useful.h, base/daemon/BaseDaemon.cpp, base/loggers/ExtendedLogChannel.cpp, base/loggers/ExtendedLogChannel.h, base/loggers/OwnPatternFormatter.cpp, src/Common/ThreadPool.cpp, src/Common/ThreadPool.h, src/Common/ThreadProfileEvents.h, src/Common/new_delete.cpp, src/Service/KeeperStore.h, src/Service/LoggerWrapper.h, src/Service/NuRaftLogSegment.h
This PR try to fix #71 
1. Remove thread status from base daemon.
2. Disable memory tracker.
3. Remove query_id form extended log channel.
=> Disable memory tracker

programs/server/config.xml, src/Service/ConnectionStats.cpp, tests/integration/test_four_word_command/test.py
Illegal `cons` command output: minlat=18446744073709551615
```
recved=0,sent=0,sid=0xffffffffffffffff,lop=NA,est=1691475923259,to=30000,lzxid=0xffffffffffffffff,lresp=0,llat=0,minlat=18446744073709551615,avglat=0,maxlat=0
```
1. Fix min latency issue
=> Fix min_latency

src/Service/ConnectionHandler.cpp, src/Service/KeeperStore.cpp, src/ZooKeeper/IKeeper.h, src/ZooKeeper/ZooKeeperCommon.cpp, src/ZooKeeper/ZooKeeperCommon.h, src/ZooKeeper/ZooKeeperConstants.cpp, src/ZooKeeper/ZooKeeperConstants.h, tests/integration/helpers/cluster_service.py, tests/integration/helpers/utils.py, tests/integration/test_back_to_back/configs/enable_keeper_three_nodes_1.xml, tests/integration/test_back_to_back/configs/enable_keeper_three_nodes_2.xml, tests/integration/test_back_to_back/configs/enable_keeper_three_nodes_3.xml, tests/integration/test_back_to_back/test.py
This PR try to close #86 
- Support multi-read ops
- remove stat in simple-list response
=> Support multi-read requests

src/Service/ConnectionHandler.cpp, src/Service/RequestProcessor.cpp
Fix too much useless warning log
```
2023.11.22 18:51:30.436301 [ 85 ] <Warning> RequestProcessor: Session 8275883 is not local, maybe it is because of disconnecting. We still should apply the committed(write) request
2023.11.22 18:51:30.475215 [ 85 ] <Warning> RequestProcessor: Session 8275885 is not local, maybe it is because of disconnecting. We still should apply the committed(write) request
2023.11.22 18:51:30.484399 [ 85 ] <Warning> RequestProcessor: Session 8275859 is not local, maybe it is because of disconnecting. We still should apply the committed(write) request
2023.11.22 18:51:30.487140 [ 85 ] <Warning> RequestProcessor: Session 8275885 is not local, maybe it is because of disconnecting. We still should apply the committed(write) request
2023.11.22 18:51:30.488113 [ 85 ] …
```
=> Fix too much warning log

src/Service/KeeperServer.cpp, src/Service/NuRaftStateManager.cpp, src/Service/NuRaftStateManager.h
This PR try to fix #104
add cluster_config_lock_ to avoid data race
=> add cluster_config_lock_ to avoid data race

src/Service/ConnectionHandler.h, tests/integration/test_four_word_command/test.py
This PR try to fix #121
If default session_id is -1, when a connection failed, server will return -1 and when client tries re-connect with previous_session_id = -1. Server receives the -1 and will identify it as a re-connection.
But actually it is not re-connection because it never success.
=> Fix illegal reconnection

programs/server/config.xml, src/Service/KeeperDispatcher.cpp, src/Service/RequestForwarder.h, src/Service/Settings.cpp, tests/integration/test_four_word_command/test.py
This PR try to fix #127 
- Set default`dead_session_check_period_ms` to 500
- Set session_sync to 2 * `dead_session_check_period_ms`
=> Set default dead_session_check_period_ms to 500

src/Service/KeeperStore.cpp, tests/integration/test_back_to_back/test.py
This PR try to fix #129
Fix handle watch trigger in `muilt` ops
=> Fix watch not triggered for `muilt` request

cmake/version.cmake, src/Service/FourLetterCommand.cpp
This PR try to fix #153
- Print timezone for built time in command mntr
Now the output like
```
zk_version	RaftKeeper v2.0.4-64c4aebac275e4d1d9e8140c09c6599b4be968b1, built on 2024-01-03 14:56:51 CST
```
=> Print timezone for built time in command mntr

programs/converter/RaftKeeperConverter.cpp
This PR try to fix #150
- Enable creating RaftKeeper snapshot logs for Converter
```
Create snapshot last_log_term 1, last_log_idx 3, size 5, nodes 5, ephemeral nodes 0, sessions 0, session_id_counter 0, zxid 0
Creating snapshot with approximately data_object_count 1, total_obj_count 4, next zxid 0, next session id 0
Begin create snapshot map object, map size 2, path /var/lib/raftkeeper/data/raft_snapshot/snapshot_20240104014721_3_1
Begin create snapshot session object, session size 0, path /var/lib/raftkeeper/data/raft_snapshot/snapshot_20240104014721_3_2
Creating snapshot nex_session_id 0x0, serialized_next_session_id 0x1
Begin create snapshot acl object, acl size 2, path /var/lib/raftkeeper/data/raft_snapshot/snapshot_20240104014721_3_3
Create new snapshot object 4, path …
```
=> Enable creating RaftKeeper snapshot logs for Converter

src/Service/KeeperStore.h
Use std::unordered_map to store watches. Since we don't need to save the path sequentially. Sortmap will perform much worse than hashmap
Use std::unordered_map to store watches.
=> Use unordered_map to store Watches

src/Service/ConnectionHandler.cpp, tests/integration/test_four_word_command/test.py
This PR try to fix #174 
Use `ConnectionHandler::onSocketWritable` to send session response to avoid deadlock.
Use `ConnectionHandler::onSocketWritable` to send session response
=> Sending session response in IO thread

src/Service/LogEntry.cpp, src/Service/LogEntry.h, src/Service/NuRaftLogSegment.cpp, src/Service/tests/gtest_raft_log.cpp
This PR try to fix #199 
- Avoid memory copy when parsing log
=> Avoid memory copy when parsing log

src/Service/ConnectionHandler.cpp, src/Service/NuRaftStateMachine.cpp
Update slow request threshold to 10s
=> Update slow request threshold

src/Service/ConnectionHandler.cpp, src/Service/NuRaftStateMachine.cpp
This PR try to fix #217
- Fix too many warning log when restarting
=> Fix too many warning log when restarting

.github/workflows/build-and-test-macos.yml, src/Service/KeeperStore.cpp, src/Service/KeeperStore.h, src/Service/NuRaftLogSnapshot.cpp, src/Service/NuRaftLogSnapshot.h, src/Service/SnapshotCommon.cpp, src/Service/SnapshotCommon.h, src/Service/tests/gtest_raft_snapshot.cpp
This PR try to fix #221
For nodes count 58680021, snapshot size 12GB
|                     | Before(sec) | After(sec) |
| ------------------- | ----------- | ---------- |
| Parse from disk     | 90          | 70         |
| Build children path | 90          | 9          |
Optimizations:
1. Reduced one buffer copy and destruction.
2. Storage edges in bucketed based on the parent node's bucket number, and built childrenSet in parallel.
3. Reserved space for childrenSet in advance.
=> Make snapshot load faster

tests/integration/test_four_word_command/test.py
This PR try to fix #224 
If there is reconnection, connections count may be non-determinastic.
Fix flaky `test test_four_word_command`
=> Fix flaky test `test_four_word_command`

src/Service/ConnectionHandler.cpp, src/Service/ConnectionHandler.h
This PR try to fix #142
Send `FIN` to 4lw client wait 4lw client to close connection, wait client close connection.
=> Send  `FIN` to 4lw client, wait 4lw client to close connection

docs/how-to-monitor-and-manage.md, src/CMakeLists.txt, src/Service/FourLetterCommand.cpp, src/Service/KeeperDispatcher.cpp, src/Service/KeeperDispatcher.h, src/Service/Metrics.cpp, src/Service/Metrics.h, src/Service/RequestAccumulator.cpp, src/Service/RequestProcessor.cpp, tests/integration/test_four_word_command/test.py
This PR is part of issue #168
Add those metrics 
- apply_read_request_time_ms: The time for request processor to process read request
- apply_write_request_time_ms: The time for request processor to process write request
- batch_size: Records the batch size of each batch accumulation for replication
- push_request_queue_time_ms: The time for push request from handler to dispatcher's request queue
- readlatency: Latency for read request. The timing start from when the server see the request until it leave final request processor
- updatelatency: Latency for write request. The timing start from when the server see the request until it leave final request processor
=> Add more metrics for mntr command

src/Service/RequestProcessor.cpp, src/Service/RequestProcessor.h
This PR try to fix #231
Before remove thread pools
Over 60% of the time in ReqProcessor is spent on `_pthread_cond_wait`.
After remove thread pools
Result for benchmark
```
#Before remove thread pools
================= Result (Time measured in microsecond.) =================
thread_size,tps,avgRT(microsecond),TP90(microsecond),TP99(microsecond),TP999(microsecond),failRate
200,84416,2407.0,3800.0,4500.0,8300.0,0.0
#After remove thread pools
================= Result (Time measured in microsecond.) =================
thread_size,tps,avgRT(microsecond),TP90(microsecond),TP99(microsecond),TP999(microsecond),failRate
200,108950,1846.0,3100.0,4000.0,5600.0,0.0
```
Remove the use of thread pools for parallel processing of read request
=> Remove the use of thread pools for parallel processing of read request

src/Service/KeeperStore.cpp, src/Service/KeeperStore.h, src/Service/NuRaftLogSnapshot.cpp, src/Service/NuRaftLogSnapshot.h, src/Service/SnapshotCommon.cpp, src/Service/SnapshotCommon.h, src/Service/tests/gtest_raft_performance.cpp
This PR try to fix #239
- remove node's lock
- remove nodeMap's lock
Slightly peformance improve
```
thread_size,tps,avgRT(microsecond),TP90(microsecond),TP99(microsecond),TP999(microsecond),failRate
200,97658,2064.0,2900.0,3700.0,5200.0,0.0
200,97157,2066.0,2900.0,3800.0,6000.0,0.0
thread_size,tps,avgRT(microsecond),TP90(microsecond),TP99(microsecond),TP999(microsecond),failRate
200,100083,2014.0,3000.0,3800.0,5500.0,0.0
200,99541,2025.0,3000.0,3700.0,5200.0,0.0
```
=> Remove unnecessary locks in keeperStore

src/Service/KeeperStore.cpp, src/Service/KeeperStore.h, src/Service/NuRaftLogSnapshot.cpp, src/Service/ZooKeeperDataReader.cpp
This PR try to fix #241 
1. Release memory when loading snapshot completes
2. Fix some logs
=> Release memory when loading snapshot completes

src/Service/KeeperStore.cpp, src/Service/KeeperStore.h, src/Service/NuRaftLogSnapshot.cpp, src/Service/NuRaftLogSnapshot.h, src/Service/NuRaftStateMachine.cpp, src/Service/SnapshotCommon.cpp, src/Service/memcopy.h
This PR try to fix #251
After #247 RaftKeeper extremely reduces the user request blocking time when creating snapshot. For an 60 million nodes keeper instance, the blocking time is about 4-5s.
But it can also speed up.
After optimization:
```
2024.05.09 23:40:51.343610 [ 1948078 ] <Information> SnapTask: Dumping data tree costs 3457ms
```
- Speed up data tree copying with SIMD and prefetching.
=> Speed up data tree copying with SIMD and prefetching.

src/Service/LastCommittedIndexManager.cpp
- Fix endless loop in last commmitted index thread
- Remove lock when pushing to last committed index manager queue
=> Fix endless loop in last commmitted index thread

src/Service/KeeperDispatcher.cpp
This PR try to fix #276 
Fix data race by using write-lock for session requests callback
=> Fix data race by using write-lock for session requests callback

src/Network/SocketReactor.cpp
This PR try to fix #282 
1. Opimize too many `getsockname` system calls
=> Opimize too many `getsockname` system calls

src/Service/KeeperDispatcher.cpp
=> Avoid ZooKeeperResponsePtr destruction in responses_queue

src/Service/NuRaftLogSnapshot.cpp, src/Service/NuRaftLogSnapshot.h, src/Service/SnapshotCommon.cpp, src/Service/SnapshotCommon.h
This PR try to fix #4
update SNAPSHOT_FILE_NAME from snapshot_{create_time}_{last_log_index}_{object_id} to snapshot_{create_time}_{last_log_term}_{last_log_index}_{object_id}
=> Save term info in snapshot filename

src/Service/KeeperCommon.h, src/Service/KeeperServer.cpp, src/Service/KeeperStore.cpp, src/Service/KeeperStore.h, src/Service/NuRaftStateMachine.cpp, src/Service/tests/gtest_raft_state_machine.cpp, tests/integration/test_back_to_back/test.py, tests/integration/test_converter/test.py, tests/integration/test_four_word_command/test.py
=> Add system nodes for keeper

src/Service/NuRaftStateMachine.cpp, src/Service/NuRaftStateMachine.h, src/Service/Settings.cpp, src/Service/Settings.h
This PR try to fix #306
- Fix creating snapshot too frequently caused int32 overflow
=> Fix creating snapshot too frequently caused by int32 overflow

src/Service/NuRaftLogSegment.cpp, src/Service/NuRaftLogSegment.h, src/Service/NuRaftStateMachine.cpp, tests/integration/test_snapshots/test.py
This PR try to fix #312
1. Fix stale log index when there is an snapshot but no log in disk
=> Fix stale log index when there is an snapshot but no log in disk

src/Service/NuRaftLogSnapshot.cpp, src/Service/NuRaftLogSnapshot.h, tests/integration/helpers/cluster_service.py, tests/integration/test_snapshots/configs/enable_async_snapshot_keeper.xml, tests/integration/test_snapshots/configs/enable_keeper.xml, tests/integration/test_snapshots/test.py
This PR try to fix #322
snapshots use term + log_index as map key since #296, we still use log_index to got snapshot to clear. So when snapshots will never update.
=> Fix snapshot never clear

CMakeLists.txt
Right now there are couple of warnings:
- /src/ch/3rd-party/RaftKeeper/base/common/types.h:269:5: error: 'switch' missing 'default' label [-Werror,-Wswitch-default]
- /src/ch/3rd-party/RaftKeeper/src/Common/ThreadProfileEvents.cpp:67:5: error: 'switch' missing 'default' label [-Werror,-Wswitch-default]
- /src/ch/3rd-party/RaftKeeper/base/common/StringRef.h:122:5: error: 'switch' missing 'default' label [-Werror,-Wswitch-default]
And likely others
=> Add ability to turn OFF -Werror

src/Common/Exception.cpp, src/Common/Exception.h, src/Service/KeeperCommon.h, src/Service/KeeperServer.cpp, src/Service/KeeperUtils.cpp, src/Service/KeeperUtils.h, src/Service/LogEntry.cpp, src/Service/LogEntry.h, src/Service/NuRaftFileLogStore.cpp, src/Service/NuRaftFileLogStore.h, src/Service/NuRaftLogSegment.cpp, src/Service/NuRaftLogSegment.h, src/Service/NuRaftLogSnapshot.cpp, src/Service/NuRaftStateMachine.cpp, src/Service/NuRaftStateMachine.h, src/Service/SnapshotCommon.cpp, src/Service/SnapshotCommon.h, src/Service/tests/gtest_raft_log.cpp, src/Service/tests/gtest_raft_snapshot.cpp, src/Service/tests/gtest_raft_state_machine.cpp, src/Service/tests/raft_test_common.cpp
This PR try to fix #321 
1. Fail fast for log error
2. Some refactoring
3. Add crc info when cloning log entry
=> Fail fast for log error

src/Service/KeeperDispatcher.cpp, src/Service/KeeperDispatcher.h
This PR try to fix #278 
- Use shared mutex for fowrard_response_callback
=> Use shared mutex for fowrard_response_callback

programs/server/config.xml, src/Service/Settings.cpp
This PR try to fix #344 
The follow testing is based on a 3-node cluster in which the node has only 1 core. 
```
parallel: 1
Benchmark result(time measured in microsecond):
parallel,tps,avgRT(us),TP90(us),TP99(us),TP999(us),wall_time(us),total_time(us),total_request,fail_request
300,60750,4899,2100.0,74300.0,100600.0,32708142,9525223470,1944000,0
parallel: 4
Benchmark result(time measured in microsecond):
parallel,tps,avgRT(us),TP90(us),TP99(us),TP999(us),wall_time(us),total_time(us),total_request,fail_request
300,63250,4705,2100.0,74700.0,89400.0,32843298,9524420480,2024000,0
```
- Add min parallel to 4
=> Add min parallel to four

src/Service/KeeperDispatcher.cpp, src/Service/KeeperDispatcher.h, src/Service/KeeperServer.cpp, src/Service/KeeperServer.h, src/Service/NuRaftFileLogStore.cpp, src/Service/NuRaftLogSegment.cpp, src/Service/NuRaftLogSegment.h, src/Service/NuRaftStateMachine.cpp, src/Service/NuRaftStateMachine.h, src/Service/SnapshotCommon.cpp, src/Service/SnapshotCommon.h, src/Service/tests/gtest_raft_log.cpp, src/Service/tests/raft_test_common.h
This PR try to fix #346 
- Fix logical error: last_segment not exist
- Remove some useless functions
=> Fix logical error: last_segment not exist

src/Service/ConnectionHandler.cpp, src/Service/KeeperDispatcher.cpp, src/Service/Metrics.h, src/Service/NuRaftStateMachine.cpp
=> Fix unexpected max latency in output of `stat`

docs/how-to-monitor-and-manage.md, src/Service/ConnectionHandler.h, src/Service/ForwardConnectionHandler.h, src/Service/FourLetterCommand.cpp, src/Service/KeeperServer.cpp, src/Service/KeeperUtils.cpp, src/Service/KeeperUtils.h, src/Service/LastCommittedIndexManager.cpp, src/Service/LastCommittedIndexManager.h, src/Service/Metrics.h, src/Service/NuRaftLogSnapshot.cpp, src/Service/NuRaftLogSnapshot.h, src/Service/NuRaftStateMachine.cpp, src/Service/NuRaftStateMachine.h, src/Service/RequestForwarder.cpp, src/Service/Settings.cpp, src/Service/Settings.h, src/Service/SnapshotCommon.cpp, src/Service/tests/gtest_raft_snapshot.cpp, src/Service/tests/gtest_raft_state_machine.cpp, src/ZooKeeper/ZooKeeperCommon.h, tests/integration/test_four_word_command/test.py
Fix #351,  Fix #266
1. Remove raftkeeper 1.0 only code
2. Use steady_lock instead of system_lock
=> Remove raftkeeper 1.0 only code

.github/workflows/github_utils.py, .github/workflows/report.py, docs/how-to-monitor-and-manage.md, programs/server/config.xml, src/Service/LoggerWrapper.cpp, src/Service/LoggerWrapper.h, src/Service/NuRaftFileLogStore.cpp, src/Service/NuRaftFileLogStore.h, src/Service/NuRaftLogSegment.cpp, src/Service/NuRaftLogSegment.h, src/Service/NuRaftStateManager.cpp, src/Service/NuRaftStateManager.h, src/Service/Settings.cpp, src/Service/Settings.h, src/Service/tests/gtest_raft_log.cpp, tests/integration/test_four_word_command/test.py, tests/integration/test_persistent_log/configs/enable_keeper.xml, tests/integration/test_persistent_log/test.py
This PR try to fix #365
1. Add configuration max_log_segment_file_size .
2. Fix illegal open segment detection.
3. Change type of MAX_LOG_SEGMENT_FILE_SIZE from uint32 to uint64 to avoid overflow
4. Little code refactoring
5. Fix duplicated comment on PR
=> Add configuration max_log_segment_file_size and fix illegal open segment detection

src/Service/ConnectionHandler.cpp, src/Service/ForwardConnection.cpp, src/Service/ForwardConnection.h, src/Service/ForwardConnectionHandler.cpp, src/Service/ForwardRequest.h, src/Service/ForwardResponse.h, src/Service/KeeperCommon.h, src/Service/KeeperStore.cpp, src/Service/KeeperUtils.cpp, src/Service/KeeperUtils.h, src/Service/RequestAccumulator.cpp, src/Service/RequestForwarder.cpp, src/Service/RequestProcessor.cpp, src/Service/RequestProcessor.h, src/Service/tests/gtest_raft_state_machine.cpp, src/Service/tests/raft_test_common.cpp
This PR try to fix #350, fix #348
- Move request to `forward_request_queue` before forward request to leader
- Use `pending_request-> create_time`(self's steady_clock) instead of `committed_request-> create_time` (leader's steady_clock) to calculate request time cost
- Standardized `forward request`, `forward response` printing in logs
=> Fix not found request for forward response

base/common/CMakeLists.txt
This PR try to fix #373
- Ignore no-switch-default-label warning
=> Fix clang 20 build error: no-switch-default-label

contrib/poco-cmake/Foundation/CMakeLists.txt, contrib/poco-cmake/XML/CMakeLists.txt, src/Common/StackTrace.cpp, src/ZooKeeper/tests/zkutil_test_commands_new_lib.cpp
This PR try to fix #319
1. Fix build error caused by deprecated event constructor
2. Fix build error in macOS with ARM
3. Update poco to 1.14.2
=> Update to poco 1.14.2
