README.md

CC&&CXX path should not be hardcoded, it should be it variable.

[enhancement](README) CC&&CXX path should not be hardcoded

---

.editorconfig

Set default charset to java files.

set default charset to java files

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/ISSUE_TEMPLATE/question.md
.github/PULL_REQUEST_TEMPLATE.md

Add PR template

---

docs/migrate-from-zookeeper.md

This PR try to fix https://github.com/JDRaftKeeper/RaftKeeper/issues/33
clear migrate doc

clear migrate doc

---

.github/workflows/build-and-test-asan.yml
src/Service/KeeperDispatcher.cpp
src/Service/NuRaftFileLogStore.cpp
src/Service/NuRaftFileLogStore.h
src/Service/RequestProcessor.cpp
tests/integration/test_persistent_log/configs/enable_keeper.xml

1. Fix ```fsyncThread``` core dump
2. Fix ```processErrorRequest``` heap use after free
3. add ASAN to CI

Fix some core dump and add asan to CI

---

CMakeLists.txt

print build flags

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/enhancement.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/ISSUE_TEMPLATE/question.md
PreLoad.cmake
cmake/linux/toolchain-aarch64.cmake
cmake/linux/toolchain-x86_64.cmake
src/Service/NuRaftFileLogStore.h
src/Service/proto/CMakeLists.txt

1. fix TSAN build error
2. fix data race

fix TSAN build error

---

build.sh

- chang build type to release in build.sh

chang build type to release

---

tests/integration/helpers/cluster_service.py
tests/integration/runner

1. make sanitizer configurable

make sanitizer configurable

---

.github/workflows/build-and-test-msan.yml
.github/workflows/run-integration-test.sh
programs/server/config.xml
src/Service/ForwardingConnectionHandler.cpp
src/Service/ForwardingConnectionHandler.h
src/Service/LogEntry.cpp
src/Service/NuRaftStateManager.cpp
src/Service/NuRaftStateManager.h
tests/integration/test_nodes_add/configs/enable_keeper_three_nodes_1.xml
tests/integration/test_nodes_add/configs/enable_keeper_three_nodes_2.xml
tests/integration/test_nodes_add/configs/enable_keeper_three_nodes_3.xml
tests/integration/test_nodes_add/configs/enable_keeper_two_nodes_1.xml
tests/integration/test_nodes_add/configs/enable_keeper_two_nodes_2.xml
tests/integration/test_nodes_add/test.py

1. Fix some msan error
2. Add config start_as_follower
3. Add msan to CI
4. Print sanitize error

Add msan to CI

---

.github/workflows/build-and-test-asan.yml
.github/workflows/build-and-test-msan.yml
.github/workflows/build-and-test-ubsan.yml
src/Common/ConcurrentBoundedQueue.h
src/Service/ForwardRequest.h
src/Service/KeeperStore.cpp
src/Service/KeeperStore.h
src/Service/RequestAccumulator.cpp
src/Service/RequestAccumulator.h
src/Service/RequestForwarder.cpp
src/Service/RequestForwarder.h
src/Service/RequestProcessor.cpp
src/Service/RequestProcessor.h
src/Service/RequestsQueue.h
src/Service/ThreadSafeQueue.h
src/Service/tests/gtest_raft_performance.cpp

1. Optimize memory copying on request and response chains
2. Adjusted denormalized ```std::forward``` and ```std::move```

Optimize memory copying on request and response chains

---

src/Service/FourLetterCommand.cpp
src/Service/FourLetterCommand.h
src/Service/KeeperDispatcher.cpp
src/Service/KeeperDispatcher.h
src/Service/Settings.cpp
version.txt

Add uptime

---

benchmark/README.md
benchmark/build.sh

Add benchmark build.sh

---

programs/server/config.xml

- Support configure core dump size

Add core dump size configuratuin to config.xml

---

.github/workflows/check-style.yml

This PR will fix #77
- Add `apt-get update` command

Fix code style tools install error

---

programs/server/Server.cpp
src/Common/NIO/SvsSocketReactor.h

This PR try to fix #80 
- add name to NIO threads

Add name to NIO threads

---

base/daemon/BaseDaemon.cpp
programs/server/Server.cpp
src/Service/KeeperDispatcher.cpp
src/Service/NuRaftStateMachine.cpp
src/Service/RequestAccumulator.cpp
src/Service/RequestForwarder.cpp
src/Service/RequestProcessor.cpp

This PR try to fix #84 
1. Add thread name to snapshot thread and signal listener thread
2. Unify thread name to `prefix`#`id`

Add thread name

---

base/glibc-compatibility/musl/COPYRIGHT
src/Service/FourLetterCommand.cpp
src/Service/KeeperDispatcher.cpp
src/Service/KeeperDispatcher.h
src/Service/Settings.cpp
src/Service/Settings.h
tests/integration/test_four_word_command/test.py
utils/check-style/codespell-ignore-words.list

Remove session_consistent

---

src/Common/NIO/PollSet.cpp
src/Common/NIO/SocketReactor.cpp

Fix data race

---

benchmark/README.md

Update benchmark docs

---

src/Service/RequestProcessor.cpp

Fix data race error in request processor

---

benchmark/README.md
src/Service/ACLMap.cpp
src/Service/ACLMap.h
src/Service/KeeperStore.cpp
src/Service/KeeperStore.h
src/Service/NuRaftStateMachine.cpp
src/Service/NuRaftStateMachine.h
src/Service/RaftTaskManager.cpp
src/Service/RaftTaskManager.h
src/Service/RequestProcessor.cpp
tests/integration/test_stale_node_recovery/configs/enable_service_keeper1.xml
tests/integration/test_stale_node_recovery/configs/enable_service_keeper2.xml
tests/integration/test_stale_node_recovery/configs/enable_service_keeper3.xml
tests/integration/test_stale_node_recovery/configs/log_conf.xml
tests/integration/test_stale_node_recovery/test.py

This PR try to fix #99 
- Reset state machine when apply snapshot from leader
/cc @lzydmxy

Reset state machine when apply snapshot from leader

---

tests/integration/test_four_word_command/test.py

This PR try to fix #103 
/cc @lzydmxy

Fix test_four_word_command occasional failure

---

src/Service/KeeperServer.cpp

This PR try to fix #110
reorder raft server shutdown

reorder raft server shutdown

---

programs/server/Server.cpp
src/Service/ForwardRequest.cpp
src/Service/KeeperServer.cpp
src/Service/RequestForwarder.cpp
src/Service/Settings.cpp
src/Service/Settings.h

`shutdown_timeout` mesured by millisecond but not second.

Fix shutdown_timeout time unit

---

programs/server/config.xml
src/Service/Settings.cpp

This PR try to fix #119 
- Enable manually creating snapshot by default

Enable manually creating snapshot by default

---

src/Service/RequestProcessor.cpp

This PR try to fix #133 
- No waiting if pending queue is not empty in request processor.

Fix request hunging in some case

---

src/Service/ForwardResponse.cpp
src/Service/ForwardResponse.h
src/Service/ForwardingConnectionHandler.cpp
src/Service/ForwardingConnectionHandler.h
src/Service/KeeperDispatcher.cpp

…der one, and add new one
This PR try to fix #117 #107
Don't throw exception when client already registered, just release older one, and add new one

Fix already registered after forward expiration

---

src/Service/KeeperStore.cpp
src/ZooKeeper/ZooKeeperCommon.cpp
src/ZooKeeper/ZooKeeperCommon.h
src/ZooKeeper/ZooKeeperConstants.cpp
src/ZooKeeper/ZooKeeperConstants.h
src/ZooKeeper/ZooKeeperIO.cpp
src/ZooKeeper/ZooKeeperIO.h
tests/integration/helpers/cluster_service.py
tests/integration/helpers/utils.py
tests/integration/test_back_to_back/test.py

This PR try to close #101  
Support FilteredList ops

Support `FilteredList` request

---

contrib/nuraft-cmake/CMakeLists.txt

This PR try to fix #134
1. Update NuRaft to lastest master branch

Update nuraft version

---

src/Service/NuRaftLogSnapshot.cpp

This PR try to fix #145
handler eof when read magic for snapshot v0

Handler eof when read magic for snapshot v0

---

src/Common/NIO/SvsSocketReactor.h

This PR try to fix #148 
- Fix IO thread name

Fix IO thread name

---

benchmark/pom.xml
benchmark/src/main/java/raftkeeper/ZooTask.java

This PR try to fix #149 
- Upgrade Zookeeper client version from 3.4.5 to 3.7.1 for benchmark tool

Upgrade Zookeeper client version to 3.7.1 for benchmark tool

---

src/Service/ForwardConnection.cpp
src/Service/RequestForwarder.cpp

This PR try to fix #159 
Fix duplicated error log in forwarder

Fix duplicated error log in forwarder

---

src/Common/ConcurrentBoundedQueue.h
src/Service/RequestsQueue.h

This PR try to fix #164 
Fix wait time unit in request queue

Fix wait time unit in request queue

---

src/Service/KeeperStore.cpp
src/Service/KeeperStore.h

This PR try to fix #162 
Fix ehpemeral nodes mutex

Fix ehpemeral nodes mutex

---

base/glibc-compatibility/glibc-compatibility.c

This PR try to fix #170 
Enable function `pthread_setname_np `

Enable function `pthread_setname_np `

---

src/Service/KeeperDispatcher.cpp
src/Service/RequestAccumulator.cpp
src/Service/RequestAccumulator.h

- Use concurrent queue in accumulator

Use concurrent queue in accumulator

---

src/Service/KeeperStore.cpp

Keep compatible with ClickHouse multiRead

---

docs/how-to-monitor-and-manage.md

Add docs `how-to-monitor-and-manage`

Add doc `how-to-monitor-and-manage`

---

CMakeLists.txt
README.md
build.sh
docs/how-to-build.md
docs/how-to-deploy.md
src/Service/FourLetterCommand.cpp
src/Service/KeeperStore.cpp

This PR try to fix #187
- `COMPATIBLE_MODE_ZOOKEEPER=ON` for Zookeeper compatible mode
- `COMPATIBLE_MODE_ZOOKEEPER=OFF` for ClickHouse compatible mode

Add build a option to support build mode

---

benchmark/README.md
benchmark/build.sh
benchmark/src/main/java/raftkeeper/ZooTask.java

Waiting for zk connection to be established in benchmark

---

src/Service/NuRaftFileLogStore.cpp

Make log append `FSYNC_BATCH` work

Make log append `FSYNC_BATCH` work

---

src/Service/ACLMap.cpp

Optimize lock for acl map

---

src/Service/ForwardRequest.h
src/Service/NuRaftStateMachine.cpp

- Fix forward request tostring

Fix forward request tostring

---

src/Service/KeeperCommon.h
src/Service/KeeperServer.h
src/Service/NuRaftStateManager.h
src/Service/RequestAccumulator.h
src/Service/RequestForwarder.h
src/Service/RequestProcessor.h
src/Service/Types.h

Remove service types.h

---

version.txt

Starting v2.0.5

---

.github/workflows/build-and-test-macos.yml
src/Common/ErrorCodes.cpp
src/NIO/PollSet.cpp

This PR try to fix #213 
- NIO framework should support macos
- Add github work flow `build-and-test-macos` to test build and run tests on MacOS.

NIO framework should support macos

---

docs/how-to-monitor-and-manage.md
src/Service/FourLetterCommand.cpp
tests/integration/test_four_word_command/test.py

This PR try to fix #219 
- Add metric is_leader

Add metric is_leader

---

.gitignore

Delete proto from git ignore file

---

src/Service/NuRaftStateMachine.cpp

Fix load snapshots bug when set log level higher than `INFO`

---

src/Service/RequestProcessor.cpp

This PR try to fix #243 
Fix extremely large max latency for error session request.

Fix extremely large max latency for error session request

---

docs/how-to-monitor-and-manage.md
src/Service/FourLetterCommand.cpp
src/Service/Metrics.cpp
src/Service/Metrics.h
src/Service/NuRaftLogSnapshot.h
src/Service/NuRaftStateMachine.cpp
src/Service/NuRaftStateMachine.h
tests/integration/test_four_word_command/test.py

This PR try to fix #248
- Add metric `snap_blocking_time_ms`
- Add new metric type `SimpleSummary`

Add metric `snap_blocking_time_ms`

---

docs/how-to-deploy.md
programs/server/config.xml

1. Adding how to deploy learner mode to how-to-deploy document

Adding how to deploy learner mode to how-to-deploy document

---

src/Service/KeeperDispatcher.cpp
src/Service/KeeperDispatcher.h

Use read-write-lock for user_response_callbacks

---

CMakeLists.txt

This PR try to fix #273 
Use cpp standard 23 instead of 20

Use cpp standard 23

---

programs/server/Server.cpp
programs/server/config.xml
src/Common/Exception.cpp
src/Common/IO/ReadBuffer.h
src/Network/SocketAcceptor.h
src/Service/KeeperStore.h
src/Service/LastCommittedIndexManager.cpp
src/Service/LastCommittedIndexManager.h
src/Service/SessionManager.h
src/Service/WatchManager.cpp
src/Service/WatchManager.h
utils/check-style/codespell-ignore-words.list

- Add configuration socket_option_no_delay

Add configuration socket_option_no_delay

---

src/Service/ConnectionHandler.cpp
src/Service/ConnectionHandler.h
src/Service/ForwardConnectionHandler.cpp
src/Service/ForwardConnectionHandler.h
src/Service/KeeperStore.cpp
src/Service/KeeperStore.h

Fix too many heart beat logs
```
2024.05.29 15:03:01.175350 [ 54 ] <Information> KeeperStore: heart beat for session 0x6121
2024.05.29 15:03:01.743013 [ 54 ] <Information> KeeperStore: heart beat for session 0x612d
2024.05.29 15:03:02.312807 [ 54 ] <Information> KeeperStore: heart beat for session 0x6136
2024.05.29 15:03:04.048490 [ 54 ] <Information> KeeperStore: heart beat for session 0x6124
2024.05.29 15:03:06.580825 [ 54 ] <Information> KeeperStore: heart beat for session 0x6126
2024.05.29 15:03:06.659991 [ 54 ] <Information> KeeperStore: heart beat for session 0x6137
```

Fix too many heart beat logs

---

src/Service/ConnectionHandler.cpp
src/Service/ConnectionHandler.h
src/Service/ConnectionStats.cpp
src/Service/ConnectionStats.h
src/Service/FourLetterCommand.cpp
src/Service/KeeperDispatcher.cpp
src/Service/KeeperDispatcher.h

This PR try to fix #288
Use atomic instead of lock for connections static

Use atomic instead of lock for connections static

---

build.sh

Update build type to RelWithDebInfo in build.sh

Update build type to RelWithDebInfo in build.sh

---

src/Service/KeeperStore.cpp
tests/integration/test_back_to_back/test.py

Don't send watch reponse if we got error in muiti writes ops

---

version.txt

Start version v2.2.0

---

src/Service/NuRaftLogSnapshot.cpp

Use local time instead of UTC for snapshot file

Use local time instead of UTC for snapshot file

---

base/daemon/BaseDaemon.cpp
cmake/warnings.cmake
contrib/boost-cmake/CMakeLists.txt
contrib/libcxx-cmake/CMakeLists.txt
contrib/libcxxabi-cmake/CMakeLists.txt
src/Common/Dwarf.cpp
src/Common/Dwarf.h
src/Common/Elf.cpp
src/Common/Elf.h

This PR try to fix #353
- Support Dwarf 5
- Build with libcxx(abi) 15

Support Dwarf 5

---

.github/workflows/pull-request.yml

Skip report test result if event is not pull request

---

.github/workflows/report.py

Fix duplicate test report in PR

---

version.txt

Start v2.3.0

---

version.txt

Change version to v2.2.1

---

src/Service/NuRaftStateMachine.cpp

Add more checking when replaying logs

---

tests/integration/test_auth/test.py

Fix flaky test_auth

---

CMakeLists.txt
cmake/find/cxx.cmake
contrib/jemalloc-cmake/CMakeLists.txt

This PR try to fix #389 
Disable jemalloc in MacOS

Disable jemalloc in MacOS
